server:
  port: 8501

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hall-service
  datasource:
    url: jdbc:mysql://192.168.40.128:3306/mooc_meetingfilm?characterEncoding=utf-8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat

mybatis-plus:
  mapper-locations: classpath*:com/mooc/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

logging:
  config: classpath:logback.xml
