server:
  port: 8203

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hello-service-provider

logging:
  config: classpath:logback.xml