mybatis-plus:
  mapper-locations: classpath*:com/mooc/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://192.168.147.129:3306/mooc_meetingfilm?characterEncoding=utf-8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml

